name: Trigger Action in Another Repo

on:
  repository_dispatch:
    types: [trigger-action]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Action in Another Repo
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.PAT }}
        repository: floorismfounder/action1
        event-type: trigger-action
